Models/Cart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PIZZA.Models
{
    public class Cart
    {
        private List<CartLine> lineCollection = new List<CartLine>();

        public void AddItem(Pizza product, int quantity)
        {
            CartLine line = lineCollection
              .Where(p => p.Product.PizzaId == product.PizzaId)
              .FirstOrDefault();

            if (line == null)
            {
                lineCollection.Add(new CartLine
                {
                    Product = product,
                    Quantity = quantity
                });
            }
            else
            {
                line.Quantity += quantity;
            }
        }

        public void RemoveLine(Pizza product)
        {
            lineCollection.RemoveAll(l => l.Product.PizzaId == product.PizzaId);
        }

        public decimal ComputeTotalValue()
        {
            return lineCollection.Sum(e => e.Product.Price * e.Quantity);
        }

        public void Clear()
        {
            lineCollection.Clear();
        }

        public IEnumerable<CartLine> Lines
        {
            get { return lineCollection; }
        }

    }
}

Models/CartLine.cs
using PIZZA.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PIZZA.Models
{
    public class CartLine
    {
        public Pizza Product { get; set; }
        public int Quantity { get; set; }
    }
    public class CartIndexViewModel
    {
        public Cart Cart { get; set; }
    }
}

Models/Order.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PIZZA.Models
{
    public class Order
    {
        [Key]
        public int Id { get; set; }
        public DateTime date { get; set; }
    }
    public class OrderViewModel
    {
        public IEnumerable<Order> orders{ get; set; }
        public IEnumerable<orderPosition> orderPositions{ get; set; }
        public IEnumerable<Pizza> Pizzas { get; set; }
        public decimal TotalPrice(int order)
        {
            decimal sum = 0;
            var piz = orderPositions.Where(c => c.orderid == order);
            foreach(var x in piz)
            {
                sum += x.quantity * Pizzas.FirstOrDefault(p => p.PizzaId == x.pizzaid).Price;
            }
            return sum;
        }
    }
}

Models/Pizza.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PIZZA.Models
{
    public class Pizza
    {
        [Key]
        public int PizzaId { get; set; }
        public string Name { get; set; }
        public string PicFile { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }

    }
}

Models/PizzaContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace PIZZA.Models
{
    public class PizzaContext: DbContext    {

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<orderPosition>()
                .HasKey(c => new { c.orderid, c.pizzaid });
        }
        public DbSet<Pizza> Pizzas { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<orderPosition> OrderPositions { get; set; }
    }
}

Models/PizzaDbInitializer.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace PIZZA.Models
{
    public class PizzaDbInitializer : DropCreateDatabaseAlways<PizzaContext>
    {
        protected override void Seed(PizzaContext db)
        {
            db.Pizzas.Add(new Pizza { Name = "Пепперони", PicFile = "Pepperoni.jpg", Description = "Cыры Моцарелла и Пармезан, шампиньоны, бекон, колбаса пепперони, помидоры, куриная грудка, чеснок, лук красный, зелень.", Price = 220 });
            db.Pizzas.Add(new Pizza { Name = "Маргарита", PicFile = "Margarita.jpg", Description = "Cыр Моцарелла, помидоры.", Price = 200 });
            db.Pizzas.Add(new Pizza { Name = "Гавайская", PicFile = "Нawaiian.jpg", Description = "Cыр Моцарелла, ветчина, ананасы.", Price = 200 });

            base.Seed(db);
        }

    }
}

Models/orderPosition.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PIZZA.Models
{
    public class orderPosition
    {
        public int orderid { get; set; }
        public int pizzaid { get; set; }
        public int quantity { get; set; }
    }
}

Controllers/CartController.cs
using PIZZA.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PIZZA.Controllers
{
    public class CartController : Controller
    {
        PizzaContext db = new PizzaContext();

        public ViewResult Index(string mes)
        {
            ViewBag.Message = mes;
            return View(new CartIndexViewModel
            {
                Cart = GetCart()
            });
        }

        public RedirectToRouteResult AddToCart(int productId, string returnUrl)
        {
            Pizza pizza = db.Pizzas.FirstOrDefault(p => p.PizzaId == productId);
            if (pizza != null)
            {
                GetCart().AddItem(pizza, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
        [HttpPost]
        public RedirectToRouteResult MakeOrder()
        {
            db.Orders.Add(new Order { date = DateTime.Now.Date});
            db.SaveChanges();
            int orderId = db.Orders.Select(c => c.Id).Max();
            foreach(var x in GetCart().Lines)
            {
                db.OrderPositions.Add(new orderPosition { orderid = orderId, pizzaid = x.Product.PizzaId, quantity = x.Quantity });
            }
            db.SaveChanges();
            GetCart().Clear();
            string mes ="Заказ оформлен!";
            return RedirectToAction("Index", new {mes});
        }

        public RedirectToRouteResult RemoveFromCart(int productId, string returnUrl)
        {
            Pizza pizza = db.Pizzas.FirstOrDefault(p => p.PizzaId == productId);
            if (pizza != null)
            {
                GetCart().RemoveLine(pizza);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        private Cart GetCart()
        {
            Cart cart = (Cart)Session["Cart"];
            if (cart == null)
            {
                cart = new Cart();
                Session["Cart"] = cart;
            }
            return cart;
        }

    }
}

Controllers/HomeController.cs
using PIZZA.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PIZZA.Controllers
{
    public class HomeController : Controller
    {
        PizzaContext db = new PizzaContext();
        public ActionResult Index()
        {
            IEnumerable<Pizza> pizzas = db.Pizzas;
            ViewBag.Pizzas = pizzas;
            return View();

        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/OrdersController.cs
using PIZZA.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PIZZA.Controllers
{
    public class OrdersController : Controller
    {
        PizzaContext db = new PizzaContext();
        // GET: Orders
        public ActionResult Index()
        {
            return View(new OrderViewModel {orders = db.Orders.ToList(), orderPositions = db.OrderPositions.ToList(), Pizzas = db.Pizzas.ToList() });
        }
    }
}

Views/Cart/Index.cshtml
@model PIZZA.Models.CartIndexViewModel

@{
    ViewBag.Title = "Index";
}

<h2>Ваша корзина</h2>
<h5>@ViewBag.Message</h5>
<table width="90%" align="center">
    <thead>
        <tr>
            <th align="center">Количество</th>
            <th align="left">Наименование</th>
            <th align="right">Цена</th>
            <th align="right">Стоимость</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.Cart.Lines)
        {
            <tr>
                <td align="center">@line.Quantity</td>
                <td align="left">@line.Product.Name</td>
                <td align="right">@line.Product.Price.ToString("c")</td>
                <td align="right">@((line.Quantity * line.Product.Price).ToString("c"))</td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" align="right">Всего:</td>
            <td align="right">
                @Model.Cart.ComputeTotalValue().ToString("c")
            </td>
        </tr>
    </tfoot>
</table>
@if (Model.Cart.Lines.Any())
{
    using (Html.BeginForm("MakeOrder", "Cart"))
    {
        <input class="btn btn-default" type="submit" value="Оформить заказ" />
    }
}
else
{
    <p>Корзина пуста</p>
}
<p align="center" class="actionButtons">
    @Html.ActionLink("Продолжить покупки", "Index", "Home")
</p>

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@model PIZZA.Models.Pizza
@{
    ViewBag.Title = "Home Page";
}



<div class="jumbotron">
    <h1>Пицца магазин</h1>
    <p class="lead">Магазин пиццы "Пицца магазин" - самое вкусное место, чтобы купить пиццу!</p>
</div>
<h1>Ассортимент</h1>
<div class="row">
    @foreach (PIZZA.Models.Pizza p in ViewBag.Pizzas)
    {

        <div class="col-md-4">
            <h2>@p.Name</h2>
            <img src="~/Content/@p.PicFile" />
            <p>
                @p.Description
            </p>
            @using (Html.BeginForm("AddToCart", "Cart"))
            {
            @Html.Hidden("productId", p.PizzaId)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <input class="btn btn-default" type="submit" value="+ Добавить в корзину" />
            }
        </div>
    }
</div>

Views/Orders/Index.cshtml
@model PIZZA.Models.OrderViewModel

<!DOCTYPE html>

<body>
    <h2>Ваши заказы</h2>
    @foreach (var x in Model.orders)
    {
        <div class="row mt-5 mb-2">
            <div>
                <h4>Заказ №@x.Id от @x.date.ToString("d")</h4>
            </div>
            <table width="90%" align="right"
                   cellpadding="10" cellspacing="10">
                <tr>
                    <th>Блюдо</th>
                    <th>Цена за шт</th>
                    <th>Количество</th>
                    <th>Цена</th>
                </tr>
                @foreach (var y in Model.orderPositions.Where(p => p.orderid == x.Id))
                {
                    var piz = @Model.Pizzas.FirstOrDefault(p => p.PizzaId == y.pizzaid);
                    <tr>
                        <td>@piz.Name</td>
                        <td>@piz.Price</td>
                        <td>@y.quantity</td>
                        @{decimal pr = piz.Price * y.quantity;}
                        <td>@pr</td>
                    </tr>
                }
                <tfoot>
                    <tr>
                        <td colspan="3" align="right">Итого:</td>
                        <td align="right">
                            @Model.TotalPrice(x.Id);
                        </td>
                    </tr>
                </tfoot>
            </table>
        </div>
    }
</body>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("PIZZA", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Ассортимент", "Index", "Home")</li>
                    <li>@Html.ActionLink("Корзина", "Index", "Cart")</li>
                    <li>@Html.ActionLink("Заказы", "Index", "Orders")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>